In [1]:
import numpy as np
from scipy.special import softmax

### Step 1: Represent the input

In [2]:
print("Step 1: Input : 3 inputs, d_model = 4")
x = np.array([[1.0, 0.0, 1.0, 0.0],     # Input 1
              [0.0, 2.0, 0.0, 2.0],     # Input 2
              [1.0, 1.0, 1.0, 1.0]])    # Input 3
print(x)

Step 1: Input : 3 inputs, d_model = 4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


### Step 2: Initializing the weight matrices

In [3]:
print("Step 2: weights 3 dimensions x d_model=4")
print("w_query")
w_query = np.array([[1, 0, 1],
                    [1, 0, 0],
                    [0, 0, 1],
                    [0, 1, 1]])
print(w_query)

Step 2: weights 3 dimensions x d_model=4
w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]


In [4]:
print("w_key")
w_key = np.array([[0, 0, 1],
                  [1, 1, 0],
                  [0, 1, 0],
                  [1, 1, 0]])
print(w_key)

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]


In [5]:
print("w_value")
w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])
print(w_value)

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


### Step 3: Matrix multiplication to obtain Q, K and V

In [6]:
print("Step 3: Matrix multiplication to obtain Q, K, V")
print("Query: x * w_query")
Q = np.matmul(x, w_query)
print(Q)

Step 3: Matrix multiplication to obtain Q, K, V
Query: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


In [7]:
print("Key: x * w_key")
K = np.matmul(x, w_key)
print(K)

Key: x * w_key
[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]


In [8]:
print("Value: x * w_value")
V = np.matmul(x, w_value)
print(V)

Value: x * w_value
[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


### Step 4: Scaled attention scores

In [9]:
print("Step 4: Scaled Attention Scores")
k_d = 1 # square root of k_d = 3 rounded down to 1 for this example
attention_scores = (Q @ K.transpose()) / k_d
print(attention_scores)

Step 4: Scaled Attention Scores
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


### Step 5: Scaled softmax attention scores for each vector

In [10]:
print("Step 5: Scaled softmax attention_scores for each vector")
attention_scores[0] = softmax(attention_scores[0])
attention_scores[1] = softmax(attention_scores[1])
attention_scores[2] = softmax(attention_scores[2])
print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])

Step 5: Scaled softmax attention_scores for each vector
[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


### Step 6: The final attention representations

In [17]:
print("Step 6: attention value obtained by score1/k_d * V")
print(V[0])
print(V[1])
print(V[2])
print("Attention 1")
attention1 = attention_scores[0].reshape(-1, 1)
attention1 = attention_scores[0][0] * V[0]
print(attention1)
print("Attention 2")
attention2 = attention_scores[0][1] * V[1]
print(attention2)
print("Attention 3")
attention3 = attention_scores[0][2] * V[2]
print(attention3)

Step 6: attention value obtained by score1/k_d * V
[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]
Attention 1
[0.06337894 0.12675788 0.19013681]
Attention 2
[0.93662106 3.74648425 0.        ]
Attention 3
[0.93662106 2.80986319 1.40493159]


### Step 7: Summing up the results

In [18]:
print("Step 7: summed the results to create the first line of the output matrix")
attention_input1 = attention1 + attention2 + attention3
print(attention_input1)


Step 7: summed the results to create the first line of the output matrix
[1.93662106 6.68310531 1.59506841]


### Step 8: Steps 1 to 7 for all the inputs

In [19]:
print("Step 8: Step 1 to 7 for inputs 1 to 3")
# We assume we have 3 results with learned weights (they were not trained in this example)
#We assume we are implementing the original Transformer paper. We will have 3 results of 64 dimensions each
attention_head1 = np.random.random((3, 64))
print(attention_head1)

Step 8: Step 1 to 7 for inputs 1 to 3
[[0.14523548 0.22365052 0.21802069 0.09946828 0.19085161 0.99158811
  0.45694771 0.02024762 0.5197738  0.38124982 0.78938322 0.70578496
  0.41760236 0.0548501  0.23151042 0.89128689 0.37582627 0.86770024
  0.29342506 0.30035858 0.13106685 0.5666362  0.39430603 0.81511467
  0.6719392  0.81454968 0.7613947  0.41750443 0.23008208 0.82018184
  0.48167661 0.01876274 0.32860761 0.10369043 0.57890781 0.01686461
  0.27720579 0.4850356  0.34908341 0.59301916 0.45722593 0.45948716
  0.43075623 0.98938185 0.08057183 0.66726703 0.56570189 0.00844507
  0.82574859 0.48820899 0.12547345 0.5440909  0.53359754 0.61170029
  0.55266888 0.32311548 0.1198441  0.10052185 0.45348993 0.36553116
  0.06558945 0.12447931 0.43258753 0.51315705]
 [0.16589669 0.38404917 0.84308113 0.52282884 0.56813039 0.87050595
  0.6487666  0.04242981 0.46917515 0.54987182 0.88137314 0.6045427
  0.53577055 0.63612882 0.16357449 0.20902301 0.08559766 0.03573224
  0.91388053 0.70434815 0.373367

### Step 9: The output of the heads of the attention sublayer

In [20]:
print("Step 9: We assume we have trained the 8 heads of the attention sublayer")
z0h1=np.random.random((3, 64))
z1h2=np.random.random((3, 64))
z2h3=np.random.random((3, 64))
z3h4=np.random.random((3, 64))
z4h5=np.random.random((3, 64))
z5h6=np.random.random((3, 64))
z6h7=np.random.random((3, 64))
z7h8=np.random.random((3, 64))
print("shape of one head", z0h1.shape, "dimension of 8 heads", 64*8)

Step 9: We assume we have trained the 8 heads of the attention sublayer
shape of one head (3, 64) dimension of 8 heads 512


### Step 10: Concatenation of the output of the heads

In [21]:
print("Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model")
output_attention = np.hstack((z0h1, z1h2, z2h3, z3h4, z4h5, z5h6, z6h7, z7h8))
print(output_attention)

Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model
[[0.06919359 0.65127053 0.46298466 ... 0.34564746 0.78835133 0.75039085]
 [0.90722625 0.26657857 0.4954622  ... 0.91038265 0.57262024 0.68896207]
 [0.56249407 0.34174224 0.58151543 ... 0.11986415 0.82669559 0.77054224]]
